# Generated by Django 4.0.4 on 2022-05-16 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='InscriptionEtudiant/imagze')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=13)),
                ('age', models.PositiveIntegerField(null=True)),
                ('matiere', models.CharField(choices=[('Sciences Mathémtiques et Informatique', 'Sciences Mathémtiques et Informatique'), ('Sciences Mathémtiques et Applications', 'Sciences Mathémtiques et Applications'), ('Sciences de la Matière Physique', 'Sciences de la Matière Physique'), ('Sciences de la Matière Chimie', 'Sciences de la Matière Chimie'), ('Sciences de la Vie', 'Sciences de la Vie'), ('Sciences de la Terre et de l univers', 'Sciences de la Terre et de l univers'), ('Cahiers des Normes Pédagogies Nationales', 'Cahiers des Normes Pédagogies Nationales')], max_length=40)),
                ('image', models.FilePathField(blank=True, null=True, path='C:\\Users\\escaper\\OneDrive\\Bureau\\projects\\face detection\\Projet\\InscriptionEtudiant\\Attendance database', recursive=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
